#!/usr/bin/env bash
set -eu

VPM_DIR="${VPM_DIR:-/usr/lib/vpm}"

. "$VPM_DIR/lib/core.sh"
. "$VPM_DIR/lib/ui.sh"

cmd="${1:-help}"
shift || true

usage(){
cat <<EOH
USAGE: vpm <Command> [args]
i, install   Install Package
r, remove    Remove Package
s, search    Search Package
u, update    Sync Repo
ug, upgrade  Upgrade System
EOH
}

case "$cmd" in
  i|install)   exec "VPM_DIR/commands/install.sh" "$@" ;;
  r|remove)    exec
  s|search)    exec
  u|update)    exec
  ug|upgrade)  exec
  *)
    log_err "Unknown Command: $cmd"
    exit 1
  ;;
esac
